// swift-tools-version: 6.0
import PackageDescription

// MARK: - MozzKit — Candidate B (offline-first, normalized local DB as source of truth)
//
// A fresh, music-centric package for Mozz. The design thesis:
//
//   * A GRDB/SQLite + FTS5 on-device database is the SINGLE SOURCE OF TRUTH.
//   * Providers (Plex, Jellyfin) sync the library CATALOG into that DB; they
//     never talk to the UI directly.
//   * The UI reads exclusively from the DB (fast, paginated, FTS-backed search).
//   * Offline downloads and per-server capability detection are first-class in
//     the schema from day one.
//   * All sync/parsing runs off the main thread.
//
// One small library per concern keeps the boundaries clean, the pure-logic
// layers unit-testable off-device, and a third backend (e.g. OpenSubsonic) a
// single new `MusicBackend` conformer rather than a rewrite.
//
// The iOS 17 app target lives in `App/` and is generated by XcodeGen
// (see `project.yml`); it links the `MozzApp` product below.
let package = Package(
    name: "MozzKit",
    platforms: [
        .iOS(.v17),
        // macOS is declared so the pure-logic layers can be unit-tested quickly
        // with `swift test` on the host, without booting a simulator. The app
        // and any iOS-only APIs are guarded with `#if os(iOS)`.
        .macOS(.v14),
    ],
    products: [
        .library(name: "MozzCore", targets: ["MozzCore"]),
        .library(name: "MozzNetworking", targets: ["MozzNetworking"]),
        .library(name: "MozzDatabase", targets: ["MozzDatabase"]),
        .library(name: "MozzPlex", targets: ["MozzPlex"]),
        .library(name: "MozzJellyfin", targets: ["MozzJellyfin"]),
        .library(name: "MozzSubsonic", targets: ["MozzSubsonic"]),
        .library(name: "MozzSync", targets: ["MozzSync"]),
        .library(name: "MozzPlayback", targets: ["MozzPlayback"]),
        .library(name: "MozzContinuity", targets: ["MozzContinuity"]),
        .library(name: "MozzHistory", targets: ["MozzHistory"]),
        .library(name: "MozzDownloads", targets: ["MozzDownloads"]),
        .library(name: "MozzRecommend", targets: ["MozzRecommend"]),
        .library(name: "MozzEnrichment", targets: ["MozzEnrichment"]),
        .library(name: "MozzApp", targets: ["MozzApp"]),

        // Cross-platform FFI spike (see spike/windows-ffi/README.md). A DYNAMIC
        // library so non-Apple hosts get a real .dll/.so to load. Additive: the
        // iOS app links MozzApp/MozzCore and is unaffected by this product.
        .library(name: "MozzFFI", type: .dynamic, targets: ["MozzFFI"]),
    ],
    dependencies: [
        // GRDB.swift — the SQLite toolkit backing our source-of-truth store and
        // FTS5 full-text search. The recommended choice for hitting the 100k-track
        // performance bar (DB-level pagination, indexed sorts, off-main writes).
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.11.0"),

        // swift-crypto — Apple's own cross-platform implementation of the
        // CryptoKit API. Needed because two pieces of *portable* logic hash:
        // the continuity queue hash (which ADR-0010 requires a non-Apple peer to
        // recompute identically) and Subsonic's MD5 token auth. `CryptoKit`
        // itself is Apple-only, so those layers could not build off-Apple.
        //
        // On Apple platforms `import Crypto` re-exports CryptoKit, so the shipping
        // iOS app keeps using the system implementation; the guarded imports below
        // make that explicit rather than implicit.
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.8.0"),
    ],
    targets: [
        // MARK: Domain core (pure Swift, no third-party deps)
        //
        // Domain models + the fresh `MusicBackend` protocol + auth/capability/
        // error types + the iOS Keychain credential store. Foundation-only so it
        // stays trivially testable off-device.
        .target(name: "MozzCore"),

        // MARK: Networking
        //
        // Async HTTPClient, Endpoint builder, URL normalization, retry/backoff,
        // and a secret-safe logger. Transport is injectable for tests.
        .target(name: "MozzNetworking", dependencies: ["MozzCore"]),

        // MARK: Source-of-truth store (GRDB + FTS5)
        //
        // Schema/migrations, record types, the read repository the UI binds to,
        // the write API the sync engine calls, and the synthetic-catalog generator
        // used by the performance harness.
        .target(
            name: "MozzDatabase",
            dependencies: ["MozzCore", "MozzHistory", .product(name: "GRDB", package: "GRDB.swift")]
        ),

        // MARK: Backends (one `MusicBackend` conformer each)
        .target(name: "MozzPlex", dependencies: ["MozzCore", "MozzNetworking"]),
        .target(name: "MozzJellyfin", dependencies: ["MozzCore", "MozzNetworking", "MozzContinuity", "MozzHistory"]),
        // Generic Subsonic / OpenSubsonic backend (Navidrome-QA'd, others
        // best-effort). Uses MD5 for classic token auth, via swift-crypto so the
        // backend builds off-Apple too.
        .target(
            name: "MozzSubsonic",
            dependencies: [
                "MozzCore", "MozzNetworking", "MozzContinuity",
                .product(name: "Crypto", package: "swift-crypto"),
            ]
        ),

        // MARK: Cross-device continuity (ADR-0010)
        //
        // Portable wire types + the `ContinuityStore` protocol for resuming
        // playback on another device. Depends on MozzCore ONLY: the backends
        // implement the store, and MozzApp maps engine types across, so
        // MozzPlayback never has to import this (which is why the queue carries
        // its own `ContinuityRepeatMode`).
        //
        // swift-crypto supplies SHA-256 for the queue hash. That hash is the one
        // value ADR-0010 requires a *non-Apple* peer to recompute byte-identically,
        // so it cannot depend on an Apple-only framework.
        .target(
            name: "MozzContinuity",
            dependencies: ["MozzCore", .product(name: "Crypto", package: "swift-crypto")]
        ),

        // MARK: Portable listening history (cross-device taste sync)
        //
        // Continuity carries the queue; this carries the *log*. No server records
        // skips or partial plays, so the local play_event log is the only copy of
        // the signal `TasteProfile` scores against — without this, listening on a
        // second device is permanently lost and the devices' recommendations
        // diverge. Events are immutable and append-only, which makes the merge a
        // G-Set union: no ordering, no locking, no compare-and-swap (which
        // ADR-0010 established no backend offers).
        .target(
            name: "MozzHistory",
            dependencies: ["MozzCore", .product(name: "Crypto", package: "swift-crypto")]
        ),

        // MARK: Catalog sync engine (backend -> DB, off-main)
        .target(name: "MozzSync", dependencies: ["MozzCore", "MozzDatabase"]),

        // MARK: Playback (AVFoundation-only)
        //
        // A gapless `AVQueuePlayer` engine with preloading, a pure/testable
        // PlayQueue (shuffle/repeat), now-playing + remote-command wiring, audio
        // session + interruption/route handling.
        .target(name: "MozzPlayback", dependencies: ["MozzCore"]),

        // MARK: Offline downloads
        //
        // URLSession background downloads, on-disk file store, DB download-state
        // + storage accounting, and the offline-first track resolver.
        .target(
            name: "MozzDownloads",
            dependencies: ["MozzCore", "MozzNetworking", "MozzDatabase"]
        ),

        // MARK: On-device recommendations (offline-first, network-free core)
        //
        // Pure taste-profile + content/sonic/collaborative recommenders behind a
        // `Recommender` port, a blender (normalize -> weighted fuse -> dedupe ->
        // drop-heard -> exploration jitter -> rank), and a `RecommendationService`
        // actor that persists ranked sets to the DB (instant + offline UI).
        // Phase 1 is fully offline (in-library "Mozz Weekly"); sonic (Core ML) and
        // collaborative (ListenBrainz) slot in as additional recommenders. See
        // docs RECOMMENDATIONS.md + ADR-0004/0005.
        .target(name: "MozzRecommend", dependencies: ["MozzCore", "MozzDatabase"]),

        // MARK: On-device sonic analysis (pure Swift, no platform frameworks)
        //
        // Turns decoded mono PCM into a fixed-width, L2-normalized feature
        // vector: the `embedding` BLOB `track_features` has reserved since v6.
        //
        // Deliberately free of every platform framework — no Accelerate, no
        // Core ML, no AVFoundation — and of any model weights. The one piece of
        // native code it does use, the vendored MP3 decoder below, is here for
        // the same reason: it is OURS on every platform rather than the host's.
        // A vector computed on an iPhone and the same track's vector computed on
        // a Pixel land in the SAME nearest-neighbour
        // index, so "the analyzer" has to be
        // one implementation, not five that agree to within rounding. That also
        // makes it testable off-device against golden fixtures in `spec/`.
        .target(name: "MozzAnalysis",
                dependencies: ["MozzCore", "CMozzMP3", "MozzNetworking", "MozzDatabase"]),

        // MARK: Vendored MP3 decoder (minimp3, CC0 — see LICENSE-minimp3.txt)
        //
        // Analysis needs PCM, and Mozz's audio lives on someone else's server.
        // All three backends will transcode to MP3 — it is the one format they
        // agree on — so MP3 is the analysis input, and the decoder has to be
        // OURS: a platform decoder per client would mean the same track decoding
        // to slightly different samples on a phone and a laptop, and therefore
        // to different vectors in a shared index.
        //
        // minimp3 is a single public-domain header with no dependencies, which
        // is the entire reason it was chosen over linking FFmpeg on five
        // platforms. The C here is a ~90-line shim over it, nothing more.
        .target(name: "CMozzMP3"),

        // MARK: Open metadata enrichment (network + orchestration; ADR-0007)
        //
        // Resolves MusicBrainz IDs (from embedded provider metadata, then
        // rate-limited MusicBrainz search) and, later, ListenBrainz similarity.
        // Persistence lives in MozzDatabase's `EnrichmentStore`, so this module
        // holds only clients + the orchestration actor, and `MozzRecommend` stays
        // network-free. Mirrors the one-client-per-service precedent of
        // MozzPlex/MozzJellyfin.
        .target(name: "MozzEnrichment", dependencies: ["MozzCore", "MozzNetworking", "MozzDatabase"]),

        // MARK: Composition root + SwiftUI feature layer (iOS)
        .target(
            name: "MozzApp",
            dependencies: [
                "MozzCore", "MozzNetworking", "MozzDatabase",
                "MozzPlex", "MozzJellyfin", "MozzSubsonic", "MozzSync",
                "MozzPlayback", "MozzDownloads", "MozzRecommend", "MozzEnrichment",
                "MozzAnalysis",
            ],
            resources: [.process("Resources")]
        ),

        // MARK: - Cross-platform FFI spike
        //
        // A thin `@_cdecl` C-ABI facade over the platform-free core, so a
        // non-Swift host (C#/.NET on Windows, Kotlin on Android) can drive it.
        // Exists to answer, on real target hardware: does the core build
        // off-Apple, does the linked SQLite have FTS5, does the C ABI hold, and
        // what does marshalling cost? See spike/windows-ffi/README.md.
        .target(
            name: "MozzFFI",
            dependencies: [
                "MozzCore", "MozzDatabase", "MozzContinuity",
                // The session facade signs in, mirrors a catalog and resolves
                // stream URLs, so it needs every backend and the sync engine.
                // These are the same modules the iOS app links; nothing here is
                // a desktop-only fork.
                "MozzNetworking", "MozzPlex", "MozzJellyfin", "MozzSubsonic", "MozzSync",
                // Recommendations and artwork/metadata enrichment are portable,
                // so linking them here is what makes them available to a Windows
                // or Android client at all — and puts them under the portability
                // CI that covers everything else in this graph.
                //
                // MozzDownloads is deliberately NOT here. It is built on a
                // background `URLSession` — `background(withIdentifier:)`,
                // `sessionSendsLaunchEvents` — which exists so transfers survive
                // the app being suspended, an iOS lifecycle concern with no
                // counterpart elsewhere, and it publishes progress with Combine.
                // A desktop client wants a plain download queue, not a port of
                // this. See ARCHITECTURE.md §0.
                "MozzRecommend", "MozzEnrichment", "MozzAnalysis",
                .product(name: "Crypto", package: "swift-crypto"),
            ]
        ),

        // MARK: - Tests
        .testTarget(name: "MozzCoreTests", dependencies: ["MozzCore"]),
        .testTarget(name: "MozzNetworkingTests", dependencies: ["MozzNetworking"]),
        .testTarget(name: "MozzDatabaseTests", dependencies: ["MozzDatabase", "MozzHistory", .product(name: "GRDB", package: "GRDB.swift")]),
        .testTarget(
            name: "MozzPlexTests",
            dependencies: ["MozzPlex", "MozzNetworking"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "MozzJellyfinTests",
            dependencies: ["MozzJellyfin", "MozzNetworking", "MozzHistory"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "MozzSubsonicTests",
            dependencies: ["MozzSubsonic", "MozzNetworking", "MozzSync", "MozzDatabase"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(name: "MozzSyncTests", dependencies: ["MozzSync", "MozzDatabase", "MozzCore"]),
        .testTarget(name: "MozzPlaybackTests", dependencies: ["MozzPlayback"]),
        .testTarget(name: "MozzContinuityTests", dependencies: ["MozzContinuity"]),
        .testTarget(name: "MozzHistoryTests", dependencies: ["MozzHistory"]),
        .testTarget(name: "MozzFFITests", dependencies: ["MozzFFI", "MozzDatabase", "MozzCore", "MozzSubsonic"]),
        .testTarget(name: "MozzDownloadsTests", dependencies: ["MozzDownloads", "MozzDatabase"]),
        .testTarget(name: "MozzRecommendTests", dependencies: ["MozzRecommend", "MozzDatabase", "MozzCore"]),
        .testTarget(name: "MozzAnalysisTests",
                    dependencies: ["MozzAnalysis", "MozzCore", "MozzDatabase"],
                    resources: [.copy("Fixtures")]),
        .testTarget(name: "MozzEnrichmentTests", dependencies: ["MozzEnrichment", "MozzNetworking", "MozzDatabase", "MozzCore"]),
        .testTarget(name: "MozzAppTests", dependencies: ["MozzApp"]),
    ],
    swiftLanguageModes: [.v5]
)
