// swift-tools-version: 6.0
import PackageDescription

// MARK: - MozzKit — Candidate B (offline-first, normalized local DB as source of truth)
//
// A fresh, music-centric package for Mozz. The design thesis:
//
//   * A GRDB/SQLite + FTS5 on-device database is the SINGLE SOURCE OF TRUTH.
//   * Providers (Plex, Jellyfin) sync the library CATALOG into that DB; they
//     never talk to the UI directly.
//   * The UI reads exclusively from the DB (fast, paginated, FTS-backed search).
//   * Offline downloads and per-server capability detection are first-class in
//     the schema from day one.
//   * All sync/parsing runs off the main thread.
//
// One small library per concern keeps the boundaries clean, the pure-logic
// layers unit-testable off-device, and a third backend (e.g. OpenSubsonic) a
// single new `MusicBackend` conformer rather than a rewrite.
//
// The iOS 17 app target lives in `App/` and is generated by XcodeGen
// (see `project.yml`); it links the `MozzApp` product below.
let package = Package(
    name: "MozzKit",
    platforms: [
        .iOS(.v17),
        // macOS is declared so the pure-logic layers can be unit-tested quickly
        // with `swift test` on the host, without booting a simulator. The app
        // and any iOS-only APIs are guarded with `#if os(iOS)`.
        .macOS(.v14),
    ],
    products: [
        .library(name: "MozzCore", targets: ["MozzCore"]),
        .library(name: "MozzNetworking", targets: ["MozzNetworking"]),
        .library(name: "MozzDatabase", targets: ["MozzDatabase"]),
        .library(name: "MozzPlex", targets: ["MozzPlex"]),
        .library(name: "MozzJellyfin", targets: ["MozzJellyfin"]),
        .library(name: "MozzSync", targets: ["MozzSync"]),
        .library(name: "MozzPlayback", targets: ["MozzPlayback"]),
        .library(name: "MozzDownloads", targets: ["MozzDownloads"]),
        .library(name: "MozzRecommend", targets: ["MozzRecommend"]),
        .library(name: "MozzApp", targets: ["MozzApp"]),
    ],
    dependencies: [
        // GRDB.swift — the SQLite toolkit backing our source-of-truth store and
        // FTS5 full-text search. The recommended choice for hitting the 100k-track
        // performance bar (DB-level pagination, indexed sorts, off-main writes).
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.11.0"),
    ],
    targets: [
        // MARK: Domain core (pure Swift, no third-party deps)
        //
        // Domain models + the fresh `MusicBackend` protocol + auth/capability/
        // error types + the iOS Keychain credential store. Foundation-only so it
        // stays trivially testable off-device.
        .target(name: "MozzCore"),

        // MARK: Networking
        //
        // Async HTTPClient, Endpoint builder, URL normalization, retry/backoff,
        // and a secret-safe logger. Transport is injectable for tests.
        .target(name: "MozzNetworking", dependencies: ["MozzCore"]),

        // MARK: Source-of-truth store (GRDB + FTS5)
        //
        // Schema/migrations, record types, the read repository the UI binds to,
        // the write API the sync engine calls, and the synthetic-catalog generator
        // used by the performance harness.
        .target(
            name: "MozzDatabase",
            dependencies: ["MozzCore", .product(name: "GRDB", package: "GRDB.swift")]
        ),

        // MARK: Backends (one `MusicBackend` conformer each)
        .target(name: "MozzPlex", dependencies: ["MozzCore", "MozzNetworking"]),
        .target(name: "MozzJellyfin", dependencies: ["MozzCore", "MozzNetworking"]),

        // MARK: Catalog sync engine (backend -> DB, off-main)
        .target(name: "MozzSync", dependencies: ["MozzCore", "MozzDatabase"]),

        // MARK: Playback (AVFoundation-only)
        //
        // A gapless `AVQueuePlayer` engine with preloading, a pure/testable
        // PlayQueue (shuffle/repeat), now-playing + remote-command wiring, audio
        // session + interruption/route handling.
        .target(name: "MozzPlayback", dependencies: ["MozzCore"]),

        // MARK: Offline downloads
        //
        // URLSession background downloads, on-disk file store, DB download-state
        // + storage accounting, and the offline-first track resolver.
        .target(
            name: "MozzDownloads",
            dependencies: ["MozzCore", "MozzNetworking", "MozzDatabase"]
        ),

        // MARK: On-device recommendations (offline-first, network-free core)
        //
        // Pure taste-profile + content/sonic/collaborative recommenders behind a
        // `Recommender` port, a blender (normalize -> weighted fuse -> dedupe ->
        // drop-heard -> exploration jitter -> rank), and a `RecommendationService`
        // actor that persists ranked sets to the DB (instant + offline UI).
        // Phase 1 is fully offline (in-library "Mozz Weekly"); sonic (Core ML) and
        // collaborative (ListenBrainz) slot in as additional recommenders. See
        // docs RECOMMENDATIONS.md + ADR-0004/0005.
        .target(name: "MozzRecommend", dependencies: ["MozzCore", "MozzDatabase"]),

        // MARK: Composition root + SwiftUI feature layer (iOS)
        .target(
            name: "MozzApp",
            dependencies: [
                "MozzCore", "MozzNetworking", "MozzDatabase",
                "MozzPlex", "MozzJellyfin", "MozzSync",
                "MozzPlayback", "MozzDownloads", "MozzRecommend",
            ],
            resources: [.process("Resources")]
        ),

        // MARK: - Tests
        .testTarget(name: "MozzCoreTests", dependencies: ["MozzCore"]),
        .testTarget(name: "MozzNetworkingTests", dependencies: ["MozzNetworking"]),
        .testTarget(name: "MozzDatabaseTests", dependencies: ["MozzDatabase", .product(name: "GRDB", package: "GRDB.swift")]),
        .testTarget(
            name: "MozzPlexTests",
            dependencies: ["MozzPlex", "MozzNetworking"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "MozzJellyfinTests",
            dependencies: ["MozzJellyfin", "MozzNetworking"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(name: "MozzSyncTests", dependencies: ["MozzSync", "MozzDatabase", "MozzCore"]),
        .testTarget(name: "MozzPlaybackTests", dependencies: ["MozzPlayback"]),
        .testTarget(name: "MozzDownloadsTests", dependencies: ["MozzDownloads", "MozzDatabase"]),
        .testTarget(name: "MozzRecommendTests", dependencies: ["MozzRecommend", "MozzDatabase", "MozzCore"]),
    ],
    swiftLanguageModes: [.v5]
)
