#!/usr/bin/env bash
# Bake the curated Tabler SVGs into an Avalonia resource dictionary of
# StreamGeometry resources, one per icon, for the desktop client.
#
# This is the desktop sibling of build-icons.sh (which feeds the iOS asset
# catalog). Both consume the SAME curated set in tools/icons/tabler-svg/, so the
# phone and the desktop draw from one source of truth and stay visually
# identical. The difference is only in the output shape: SwiftUI wants template
# imagesets, Avalonia wants Path geometry.
#
#   Source SVGs:  tools/icons/tabler-svg/*.svg
#   Output:       clients/desktop/Assets/Icons.axaml
#
# Why geometry rather than shipping the SVGs? Avalonia has no built-in SVG
# decoder; a <Path>/<PathIcon> fed a StreamGeometry inherits Foreground, scales
# to any size with no raster step, and needs no third-party parser at runtime.
# So we lift the path data out at build time and let the XAML compiler turn it
# into geometry.
#
# Tabler icons are stroke-based on a 24x24 grid. The consuming styles render the
# stroke ones with Stroke + round caps/joins; the few solid ones (play, pause,
# the skip arrows) are authored fill="currentColor" and get an F1 (nonzero)
# fill-rule prefix so overlapping sub-paths fill the way SVG intends.
#
# Adding an icon: drop its SVG in tools/icons/tabler-svg/ (from tabler.io/icons,
# MIT), add a line to ICONS below, and re-run. No hand-editing of Icons.axaml.
set -euo pipefail
cd "$(dirname "$0")/../.."

SVG_DIR="tools/icons/tabler-svg"
OUT="clients/desktop/Assets/Icons.axaml"

# "<svg-basename> <ResourceKeySuffix>" — the key becomes Icon<Suffix>.
# Curated to exactly what the desktop UI draws; keep it a subset, not a dump of
# the whole folder, so the generated dictionary stays legible.
ICONS="
arrows-shuffle      Shuffle
chevron-left        ChevronLeft
player-skip-back    SkipBack
player-play         Play
player-pause        Pause
player-skip-forward SkipForward
repeat              Repeat
list                Queue
volume              Volume
home                Home
music               Music
disc                Disc
user-circle         Artist
playlist            Playlist
server              Server
search              Search
heart-filled        Heart
heart               HeartOutline
category            Settings
refresh             Refresh
waveform            Waveform
quote               Quote
sparkles            Sparkles
stack-3             Stack
palette             Palette
stethoscope         Stethoscope
check               Check
circle-x            CircleX
info-circle         Info
code                Code
star                Star
x                   X
"

tmp="${OUT}.tmp"
{
  echo '<!--'
  echo '  GENERATED by tools/icons/build-desktop-icons.sh from tools/icons/tabler-svg/*.svg.'
  echo '  Do not edit by hand. Tabler Icons are MIT-licensed (https://tabler.io/icons).'
  echo '-->'
  echo '<ResourceDictionary xmlns="https://github.com/avaloniaui"'
  echo '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">'
} > "$tmp"

count=0
while read -r name key; do
  [ -z "$name" ] && continue
  svg="$SVG_DIR/$name.svg"
  if [ ! -e "$svg" ]; then
    echo "missing: $svg" >&2
    exit 1
  fi

  # Concatenate every sub-path's `d` into one geometry string. Each starts with
  # an absolute M, so back-to-back they read as independent sub-paths.
  data=$(grep -o 'd="[^"]*"' "$svg" | sed 's/^d="//; s/"$//' | tr '\n' ' ' | sed 's/  */ /g; s/ *$//')

  # Solid glyphs carry fill="currentColor" and no stroke; stroke glyphs are the
  # opposite. The fill-rule prefix only matters for the solid ones.
  if grep -q 'fill="currentColor"' "$svg"; then
    data="F1 $data"
  fi

  printf '    <StreamGeometry x:Key="Icon%s">%s</StreamGeometry>\n' "$key" "$data" >> "$tmp"
  count=$((count + 1))
done <<EOF
$ICONS
EOF

echo '</ResourceDictionary>' >> "$tmp"
mv "$tmp" "$OUT"
echo "Wrote ${count} geometries to ${OUT}"
